#!/bin/bash
IP=192.168.178.60
HEXFILE=.pioenvs/yun/firmware.hex
scp $HEXFILE root@$IP:/root/firmware.hex
ssh root@$IP 'merge-sketch-with-bootloader.lua firmware.hex'
ssh root@$IP 'run-avrdude firmware.hex '
